import svg2ttf from 'svg2ttf'
import ttf2woff from 'ttf2woff'
import { compress } from 'woff2-encoder'
import type { Project } from '@iconotype/core-model'
import { buildSvgFont, type BuildWarning, type BuiltGlyph, type SvgFontResult } from './svgfont.js'
import type { FontMetrics } from './metrics.js'

export type FontFormat = 'svg' | 'ttf' | 'woff' | 'woff2'

export interface BuildOptions {
  formats?: FontFormat[]
  /**
   * Deterministic build stamp in seconds. NEVER Date.now() — identical input must
   * produce identical bytes or CI caching and `diff` are meaningless.
   */
  timestamp?: number
}

export interface FontBuild {
  svg: string
  ttf?: Uint8Array
  woff?: Uint8Array
  woff2?: Uint8Array
  glyphs: BuiltGlyph[]
  metrics: FontMetrics
  warnings: BuildWarning[]
  ligatureChars: string[]
}

const bytes = (v: Uint8Array | { buffer: ArrayBufferLike } | ArrayBuffer): Uint8Array =>
  v instanceof Uint8Array ? v : v instanceof ArrayBuffer ? new Uint8Array(v) : new Uint8Array(v.buffer)

/**
 * Project → font binaries.
 *
 * Writer is svg2ttf, not opentype.js. Three measured reasons (docs/12):
 *   - opentype.js emits CFF/`OTTO`, not a glyf TTF
 *   - its `head.modified` is always `now()`, so output is never byte-stable
 *   - `Path.fromSVG` y-flips per glyph using that glyph's own bounding box
 * svg2ttf has none of those, and gives ligature GSUB for free.
 * opentype.js is still the right tool for READING fonts.
 */
/**
 * `ttf2woff` is written against Node's Buffer, and a browser has none.
 *
 * It is the only step in the pipeline that needs one: svg2ttf is plain arrays and the
 * WOFF2 encoder is wasm. So the polyfill is fetched at the moment WOFF is asked for and
 * never otherwise — Node and the CLI never load it at all, and a browser that only
 * builds WOFF2 does not pay for it either.
 *
 * Without this, "Download package" in the web app failed with "Buffer is not defined"
 * for every project with WOFF among its formats, which is the default.
 */
export async function ensureBuffer(target: { Buffer?: unknown } = globalThis): Promise<void> {
  if (typeof target.Buffer !== 'undefined') return
  const { Buffer } = await import('buffer/index.js')
  target.Buffer = Buffer
}

export async function buildFont(project: Project, opts: BuildOptions = {}): Promise<FontBuild> {
  const formats = new Set<FontFormat>(opts.formats ?? ['svg', 'ttf', 'woff', 'woff2'])
  const source: SvgFontResult = buildSvgFont(project)
  const build: FontBuild = {
    svg: source.svg,
    glyphs: source.glyphs,
    metrics: source.metrics,
    warnings: [...source.warnings],
    ligatureChars: source.ligatureChars,
  }

  const needsTtf = formats.has('ttf') || formats.has('woff') || formats.has('woff2')
  if (!needsTtf) return build

  // name-table metadata: what a font inspector, and any licence audit, will read
  const meta = project.preferences.font.metadata ?? {}
  const ttf = bytes(svg2ttf(source.svg, {
    ts: opts.timestamp ?? 0,
    version: `Version ${project.preferences.font.majorVersion}.${project.preferences.font.minorVersion}`,
    description: meta.description ?? 'Generated by Iconotype',
    ...(meta.copyright ? { copyright: meta.copyright } : {}),
    ...(meta.url ?? meta.designerURL ? { url: meta.url ?? meta.designerURL } : {}),
  }).buffer)

  if (formats.has('ttf')) build.ttf = ttf
  if (formats.has('woff')) {
    await ensureBuffer()
    build.woff = bytes(ttf2woff(ttf, { metadata: undefined }))
  }
  if (formats.has('woff2')) {
    try {
      build.woff2 = bytes(await compress(ttf))
    } catch (e) {
      build.warnings.push({ code: 'WOFF2_FAILED', message: `WOFF2 encoding failed: ${(e as Error).message}` })
    }
  }
  return build
}

/** `icon-home` etc. — the class name a consumer writes in their markup. */
export const classNameFor = (project: Project, glyph: BuiltGlyph): string =>
  `${project.preferences.font.prefix}${glyph.name.replace(/-path\d+$/, '')}${project.preferences.font.postfix}`
