import type { Project } from '@iconotype/core-model'
import { identifier, pascalCase, resolveFormat, xmlEscape, type FormatOptions } from './options.js'
import { iconsOf, type IconEntry } from './svg.js'

/**
 * Framework component emitters.
 *
 * Every one produces a SINGLE component that switches on a name, rather than one file
 * per icon: it tree-shakes just as well when the name is a literal, and it keeps the
 * generated surface small enough to review in a diff.
 */

export type ComponentTarget = 'react' | 'vue' | 'svelte' | 'webcomponent' | 'elm'

const paths = (entry: IconEntry): string =>
  entry.glyph.paths
    .map((d, i) => {
      const fill = entry.glyph.attrs[i]?.fill
      return fill ? `<path fill="${xmlEscape(fill)}" d="${d}"/>` : `<path d="${d}"/>`
    })
    .join('')

const iconMap = (entries: IconEntry[]): string =>
  entries
    .map((e) => `  '${e.glyph.name}': ['${e.set.height}', '${paths(e)}'],`)
    .join('\n')

export function exportReact(project: Project, entries: IconEntry[], options: FormatOptions = {}): string {
  const opts = resolveFormat(options)
  const name = pascalCase(project.preferences.font.family) || 'Icon'
  return `// Generated by Iconotype. Do not edit.
import { type SVGProps } from 'react'

const ICONS = {
${iconMap(entries)}
} as const

export type ${name}Name = keyof typeof ICONS

export interface ${name}Props extends SVGProps<SVGSVGElement> {
  name: ${name}Name
  size?: number | string
  title?: string
}

export function ${name}({ name, size = ${opts.size}, title, ...rest }: ${name}Props) {
  const [box, body] = ICONS[name]
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox={\`0 0 \${box} \${box}\`}
      fill="currentColor"
      role={title ? 'img' : 'presentation'}
      aria-hidden={title ? undefined : true}
      {...rest}
      dangerouslySetInnerHTML={{ __html: (title ? \`<title>\${title}</title>\` : '') + body }}
    />
  )
}

export const ${name.toLowerCase()}Names = Object.keys(ICONS) as ${name}Name[]
`
}

export function exportVue(project: Project, entries: IconEntry[], options: FormatOptions = {}): string {
  const opts = resolveFormat(options)
  const name = pascalCase(project.preferences.font.family) || 'Icon'
  return `<!-- Generated by Iconotype. Do not edit. -->
<script setup lang="ts">
import { computed } from 'vue'

const ICONS: Record<string, [string, string]> = {
${iconMap(entries)}
}

const props = withDefaults(defineProps<{ name: keyof typeof ICONS; size?: number | string; title?: string }>(), {
  size: ${opts.size},
})

const icon = computed(() => ICONS[props.name as string] ?? ['24', ''])
const body = computed(() => (props.title ? \`<title>\${props.title}</title>\` : '') + icon.value[1])
</script>

<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    :width="size"
    :height="size"
    :viewBox="\`0 0 \${icon[0]} \${icon[0]}\`"
    fill="currentColor"
    :role="title ? 'img' : 'presentation'"
    :aria-hidden="title ? undefined : true"
    v-html="body"
  />
</template>
`
}

export function exportSvelte(project: Project, entries: IconEntry[], options: FormatOptions = {}): string {
  const opts = resolveFormat(options)
  return `<!-- Generated by Iconotype. Do not edit. -->
<script lang="ts">
  const ICONS: Record<string, [string, string]> = {
${iconMap(entries)}
  }

  let { name, size = ${opts.size}, title, ...rest }: {
    name: keyof typeof ICONS
    size?: number | string
    title?: string
  } & Record<string, unknown> = $props()

  const icon = $derived(ICONS[name as string] ?? ['24', ''])
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width={size}
  height={size}
  viewBox="0 0 {icon[0]} {icon[0]}"
  fill="currentColor"
  role={title ? 'img' : 'presentation'}
  aria-hidden={title ? undefined : true}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html icon[1]}
</svg>
`
}

export function exportWebComponent(project: Project, entries: IconEntry[], options: FormatOptions = {}): string {
  const opts = resolveFormat(options)
  const tag = `${opts.prefix.replace(/-$/, '')}-icon`
  return `// Generated by Iconotype. Do not edit.
const ICONS = {
${iconMap(entries)}
}

/** <${tag} name="home" size="24"></${tag}> */
export class IconotypeIcon extends HTMLElement {
  static observedAttributes = ['name', 'size', 'title']

  connectedCallback() { this.#render() }
  attributeChangedCallback() { this.#render() }

  #render() {
    const entry = ICONS[this.getAttribute('name')]
    if (!entry) { this.replaceChildren(); return }
    const [box, body] = entry
    const size = this.getAttribute('size') ?? '${opts.size}'
    const title = this.getAttribute('title')
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
    svg.setAttribute('viewBox', \`0 0 \${box} \${box}\`)
    svg.setAttribute('width', size)
    svg.setAttribute('height', size)
    svg.setAttribute('fill', 'currentColor')
    svg.setAttribute('aria-hidden', title ? 'false' : 'true')
    // innerHTML on an SVG element is namespace-safe in every browser that supports custom elements
    svg.innerHTML = (title ? \`<title>\${title}</title>\` : '') + body
    this.replaceChildren(svg)
  }
}

if (!customElements.get('${tag}')) customElements.define('${tag}', IconotypeIcon)
`
}

/**
 * Elm has no way to inject raw markup, so each icon is emitted as real `Svg.path`
 * nodes rather than a string the way the other targets do.
 */
export function exportElm(project: Project, entries: IconEntry[]): string {
  const moduleName = pascalCase(project.preferences.font.family) || 'Icons'
  const fn = (e: IconEntry) => {
    const name = identifier(e.glyph.name)
    const nodes = e.glyph.paths
      .map((d, i) => {
        const fill = e.glyph.attrs[i]?.fill
        const attrs = [`A.d "${d}"`, ...(fill ? [`A.fill "${fill}"`] : [])].join(', ')
        return `${i === 0 ? '        [ ' : '        , '}Svg.path [ ${attrs} ] []`
      })
      .join('\n')
    return `${name} : Int -> Svg msg
${name} size =
    icon size "${e.set.height}"
${nodes}
        ]`
  }
  const exposed = entries.map((e) => identifier(e.glyph.name)).join(', ')
  return `-- Generated by Iconotype. Do not edit.


module ${moduleName} exposing (${exposed || '..'})

import Svg exposing (Svg)
import Svg.Attributes as A


icon : Int -> String -> List (Svg msg) -> Svg msg
icon size box children =
    Svg.svg
        [ A.viewBox ("0 0 " ++ box ++ " " ++ box)
        , A.width (String.fromInt size)
        , A.height (String.fromInt size)
        , A.fill "currentColor"
        ]
        children


${entries.map(fn).join('\n\n\n')}
`
}

/** A TypeScript declaration of every icon name, so a typo is a compile error. */
export function exportTypes(project: Project, entries: IconEntry[]): string {
  const family = pascalCase(project.preferences.font.family) || 'Icon'
  const names = entries.map((e) => `  | '${e.glyph.name}'`).join('\n')
  const consts = entries
    .map((e) => {
      const cp = project.codepoints[e.glyph.name]
      const first = Array.isArray(cp) ? cp[0]! : cp
      return `  ${identifier(e.glyph.name)}: '${e.glyph.name}',${first === undefined ? '' : ` // \\u${first.toString(16)}`}`
    })
    .join('\n')
  return `// Generated by Iconotype. Do not edit.

export type ${family}Name =
${names || "  | never"}

export const ${family}Names = {
${consts}
} as const satisfies Record<string, ${family}Name>

export const all${family}Names: ${family}Name[] = Object.values(${family}Names)
`
}

export function exportComponent(
  target: ComponentTarget, project: Project, entries: IconEntry[], options: FormatOptions = {},
): string {
  switch (target) {
    case 'react': return exportReact(project, entries, options)
    case 'vue': return exportVue(project, entries, options)
    case 'svelte': return exportSvelte(project, entries, options)
    case 'webcomponent': return exportWebComponent(project, entries, options)
    case 'elm': return exportElm(project, entries)
  }
}

export const componentFilename = (target: ComponentTarget, project: Project): string => {
  const name = pascalCase(project.preferences.font.family) || 'Icon'
  switch (target) {
    case 'react': return `${name}.tsx`
    case 'vue': return `${name}.vue`
    case 'svelte': return `${name}.svelte`
    case 'webcomponent': return `${name.toLowerCase()}-element.js`
    case 'elm': return `${name}.elm`
  }
}

export { iconsOf }
