import type { Project } from '@glyphsmith/core-model'
import { groupIcons, type FontBuild } from '@glyphsmith/core-font'
import { identifier, pascalCase } from './options.js'

/**
 * A Flutter `IconData` class — IcoMoon's "Dart Class for Flutter" output.
 *
 * Flutter references glyphs by codepoint against a font family declared in
 * pubspec.yaml, so this is a class of constants rather than any kind of asset.
 */
export function exportDart(project: Project, build: FontBuild, options: { package?: string } = {}): string {
  const family = project.preferences.font.family
  const className = pascalCase(family) || 'Icons'
  const pkg = options.package ? `\n    fontPackage: '${options.package}',` : ''

  const constants = groupIcons(build.glyphs).map(({ name, layers }) => {
    const identifierName = identifier(name)
    const code = layers[0]!.code
    return `  static const IconData ${identifierName} = IconData(0x${code.toString(16)}, fontFamily: _family${options.package ? ', fontPackage: _package' : ''});`
  })

  return `// Generated by Glyphsmith. Do not edit.
//
// Declare the font in pubspec.yaml:
//
//   flutter:
//     fonts:
//       - family: ${family}
//         fonts:
//           - asset: fonts/${family}.ttf
import 'package:flutter/widgets.dart';

class ${className} {
  ${className}._();

  static const String _family = '${family}';${options.package ? `\n  static const String _package = '${options.package}';` : ''}
${constants.join('\n')}
}
${pkg ? '' : ''}`
}
