import type { OutputConfig, Paths, Project, StyleOutput } from '@iconotype/core-model'
import { asPaths, firstPath } from '@iconotype/core-model'
import { buildCss, buildDemoHtml, buildFont, buildVariables, groupIcons, type FontBuild } from '@iconotype/core-font'
import { exportDart } from './dart.js'
import { exportSpriteSymbols } from './svg.js'
import { exportTypes } from './components.js'
import { iconsOf } from './svg.js'
import { clean, relativeFontPath } from './layout.js'

/**
 * Direct export: font files and stylesheets written straight to their configured paths,
 * rather than bundled into a zip for a human to unpack.
 *
 * This is what makes an icon font part of a build. Fonts land where webpack (or vite,
 * or whatever) already looks, and the stylesheet is regenerated in place.
 */

export interface OutputFile {
  /** workspace-relative path */
  path: string
  data: Uint8Array | string
  /** what produced it, for reporting */
  kind: 'font' | 'style' | 'types' | 'sprite' | 'demo'
}


const escape = (code: number) => `\\${code.toString(16)}`

/** `$app-home: "\e900";` and friends — the variables-only style outputs. */
function buildVariableBlock(
  project: Project, build: FontBuild, kind: StyleOutput['kind'], fontPath: string,
): string {
  const prefix = project.preferences.font.prefix
  const icons = groupIcons(build.glyphs)
  const rows = icons.map(({ name, layers }) => ({ name, code: layers[0]!.code }))

  switch (kind) {
    case 'scss-variables':
      return buildVariables(project, build, 'scss', { fontPath })
    case 'less-variables':
      return buildVariables(project, build, 'less', { fontPath })
    case 'css-variables':
      return [
        `/* ${project.preferences.font.family} codepoints — generated by Iconotype */`,
        ':root {',
        ...rows.map((r) => `  --${prefix}${r.name}: "${escape(r.code)}";`),
        '}',
        '',
      ].join('\n')
    case 'json':
      return JSON.stringify(Object.fromEntries(rows.map((r) => [r.name, r.code.toString(16)])), null, 2) + '\n'
    case 'dart':
      return exportDart(project, build)
    default:
      return ''
  }
}

export interface ResolveOptions {
  /** deterministic build stamp; never Date.now() */
  timestamp?: number
  /** override the version query appended to font urls */
  version?: string
}

/**
 * Produces every file the project's `output` config asks for, ready to write.
 * Nothing here touches a filesystem — the caller (extension, CLI) writes them.
 */
export async function resolveOutputs(
  project: Project, options: ResolveOptions = {},
): Promise<{ files: OutputFile[]; build: FontBuild }> {
  const output: OutputConfig = project.output ?? {}
  const family = project.preferences.font.family
  const formats = output.fonts?.formats ?? ['woff2', 'woff', 'ttf']

  const build = await buildFont(project, { formats, timestamp: options.timestamp ?? 0 })
  const files: OutputFile[] = []

  /** the same bytes, once per destination the config names */
  const emit = (paths: Paths | undefined, data: Uint8Array | string, kind: OutputFile['kind']) => {
    for (const path of asPaths(paths)) files.push({ path: clean(path), data, kind })
  }

  const fontDirs = asPaths(output.fonts?.dir).map((dir) => clean(dir).replace(/\/*$/, '/'))
  for (const dir of fontDirs) {
    for (const format of formats) {
      const data = format === 'svg' ? build.svg : build[format]
      if (data) files.push({ path: `${dir}${family}.${format}`, data, kind: 'font' })
    }
  }

  for (const style of output.styles ?? []) {
    /**
     * A stylesheet written to two places still carries ONE font url.
     *
     * Two copies of the same sheet at different depths would each want a different
     * `../`, and there is no way to satisfy both from one file — so the url is
     * computed for the first destination, and a project that needs otherwise sets
     * `publicPath` to something absolute, which is the honest fix anyway.
     */
    const fontPath = output.fonts
      ? (output.fonts.publicPath ?? relativeFontPath(firstPath(style.path), firstPath(output.fonts.dir)))
      : 'fonts/'
    const data =
      style.kind === 'css' || style.kind === 'scss' || style.kind === 'less'
        ? buildCss(project, build, { fontPath, formats, version: options.version })
        : buildVariableBlock(project, build, style.kind, fontPath)
    emit(style.path, data, 'style')
  }

  const entries = iconsOf(project).filter((e) => e.glyph.selected !== false)
  if (output.types) emit(output.types.path, exportTypes(project, entries), 'types')
  if (output.sprite) emit(output.sprite.path, exportSpriteSymbols(project, entries), 'sprite')
  if (output.demo) emit(output.demo.path, buildDemoHtml(project, build), 'demo')

  return { files, build }
}
