import type { OutputConfig, Project, StyleOutput } from '@iconotype/core-model'
import { buildCss, buildDemoHtml, buildFont, buildVariables, groupIcons, type FontBuild } from '@iconotype/core-font'
import { exportDart } from './dart.js'
import { exportSpriteSymbols } from './svg.js'
import { exportTypes } from './components.js'
import { iconsOf } from './svg.js'
import { clean, relativeFontPath } from './layout.js'

/**
 * Direct export: font files and stylesheets written straight to their configured paths,
 * rather than bundled into a zip for a human to unpack.
 *
 * This is what makes an icon font part of a build. Fonts land where webpack (or vite,
 * or whatever) already looks, and the stylesheet is regenerated in place.
 */

export interface OutputFile {
  /** workspace-relative path */
  path: string
  data: Uint8Array | string
  /** what produced it, for reporting */
  kind: 'font' | 'style' | 'types' | 'sprite' | 'demo'
}


const escape = (code: number) => `\\${code.toString(16)}`

/** `$app-home: "\e900";` and friends — the variables-only style outputs. */
function buildVariableBlock(
  project: Project, build: FontBuild, kind: StyleOutput['kind'], fontPath: string,
): string {
  const prefix = project.preferences.font.prefix
  const icons = groupIcons(build.glyphs)
  const rows = icons.map(({ name, layers }) => ({ name, code: layers[0]!.code }))

  switch (kind) {
    case 'scss-variables':
      return buildVariables(project, build, 'scss', { fontPath })
    case 'less-variables':
      return buildVariables(project, build, 'less', { fontPath })
    case 'css-variables':
      return [
        `/* ${project.preferences.font.family} codepoints — generated by Iconotype */`,
        ':root {',
        ...rows.map((r) => `  --${prefix}${r.name}: "${escape(r.code)}";`),
        '}',
        '',
      ].join('\n')
    case 'json':
      return JSON.stringify(Object.fromEntries(rows.map((r) => [r.name, r.code.toString(16)])), null, 2) + '\n'
    case 'dart':
      return exportDart(project, build)
    default:
      return ''
  }
}

export interface ResolveOptions {
  /** deterministic build stamp; never Date.now() */
  timestamp?: number
  /** override the version query appended to font urls */
  version?: string
}

/**
 * Produces every file the project's `output` config asks for, ready to write.
 * Nothing here touches a filesystem — the caller (extension, CLI) writes them.
 */
export async function resolveOutputs(
  project: Project, options: ResolveOptions = {},
): Promise<{ files: OutputFile[]; build: FontBuild }> {
  const output: OutputConfig = project.output ?? {}
  const family = project.preferences.font.family
  const formats = output.fonts?.formats ?? ['woff2', 'woff', 'ttf']

  const build = await buildFont(project, { formats, timestamp: options.timestamp ?? 0 })
  const files: OutputFile[] = []

  if (output.fonts) {
    const dir = clean(output.fonts.dir).replace(/\/*$/, '/')
    for (const format of formats) {
      const data = format === 'svg' ? build.svg : build[format]
      if (data) files.push({ path: `${dir}${family}.${format}`, data, kind: 'font' })
    }
  }

  for (const style of output.styles ?? []) {
    const fontPath = output.fonts
      ? (output.fonts.publicPath ?? relativeFontPath(style.path, output.fonts.dir))
      : 'fonts/'
    const data =
      style.kind === 'css' || style.kind === 'scss' || style.kind === 'less'
        ? buildCss(project, build, { fontPath, formats, version: options.version })
        : buildVariableBlock(project, build, style.kind, fontPath)
    files.push({ path: clean(style.path), data, kind: 'style' })
  }

  const entries = iconsOf(project).filter((e) => e.glyph.selected !== false)
  if (output.types) files.push({ path: clean(output.types.path), data: exportTypes(project, entries), kind: 'types' })
  if (output.sprite) files.push({ path: clean(output.sprite.path), data: exportSpriteSymbols(project, entries), kind: 'sprite' })
  if (output.demo) files.push({ path: clean(output.demo.path), data: buildDemoHtml(project, build), kind: 'demo' })

  return { files, build }
}
