import * as vscode from 'vscode'
import { outputPaths } from '@iconotype/core-export/layout'
import { asPaths, type Paths } from '@iconotype/core-model'
import { resolveOutputConfig } from './export.js'
import { referencePattern } from './language.js'
import type { IconFont, IconFontRegistry, IconRef } from './registry.js'

/**
 * Where each icon is actually used in the workspace.
 *
 * Answers the two questions that matter when a font grows: "can I delete this icon?"
 * and "what does this class in the markup actually look like?". Unused icons are the
 * ones worth deselecting, which is why the panel groups by icon rather than by file.
 */

export interface UsageSite {
  uri: vscode.Uri
  line: number
  column: number
  text: string
  /** the prefix this site was written with — a project may use more than one */
  prefix: string
}

export interface IconUsage {
  icon: IconRef
  sites: UsageSite[]
}

const DEFAULT_INCLUDE = '**/*.{html,htm,css,scss,less,js,jsx,mjs,cjs,ts,tsx,vue,svelte,astro,md,mdx,php,erb,hbs,xml,json,dart,kt,swift,java}'

/**
 * Directories worth never reading, by name at any depth.
 *
 * Beyond the obvious: a mobile app repo carries `platforms/`, `Pods/` and `.gradle/`
 * full of generated copies of the source, and a vendored `.yarn/` can be tens of
 * thousands of files. In one real project the scan hit its file cap inside those and
 * never reached `app/` at all, so every icon looked unused.
 *
 * This is the default of `iconotype.usage.excludeDirs`, so it is visible and editable
 * in the settings UI rather than buried here — remove an entry to scan it.
 */
export const DEFAULT_EXCLUDE_DIRS = [
  'node_modules', 'dist', 'build', 'out', 'target', 'coverage', 'vendor', 'platforms', 'Pods',
  '.git', '.gradle', '.yarn', '.bundle', '.svelte-kit', '.next', '.nuxt', '.output', '.venv', '__pycache__',
]

/** `**\/{a,b}/**` for a list of directory names. */
export const excludeGlobFor = (dirs: Iterable<string>): string => {
  const names = [...new Set([...dirs].map((d) => d.trim().replace(/^\*\*\//, '').replace(/\/\*\*$/, '')).filter(Boolean))]
  return names.length ? `**/{${names.join(',')}}/**` : ''
}

/** Raised from 5000, which a large repo blows through before reaching its own source. */
const DEFAULT_FILE_LIMIT = 40_000

export interface ScanReport {
  /** files actually read */
  files: number
  /** true when the file limit stopped the scan short — never let this be silent */
  truncated: boolean
}

/**
 * Stylesheets a build wrote, recognised by their own header.
 *
 * The paths a Iconotype export writes are known exactly, but a project also carries
 * output from before it was one — an IcoMoon `style.css`, a stale `icons.scss` — and
 * those name every icon in the font. Counting them makes everything look used.
 */
export function isGeneratedStylesheet(uri: vscode.Uri, text: string): boolean {
  if (!/\.(css|scss|less|sass|styl)$/i.test(uri.path)) return false
  const head = text.slice(0, 600)
  return /generated by (?:Iconotype)/i.test(head)
    || /Do not edit(?: this file)? (?:by hand|directly)/i.test(head)
    || /generated by icomoon/i.test(head)
    || (/@font-face\s*\{/.test(text) && /url\(['"]?[^'")]*\.(woff2?|ttf|eot)/i.test(text))
}

export class UsageIndex {
  #usage = new Map<string, IconUsage>()
  /** files skipped because a build wrote them — offered as links instead */
  #generated = new Set<string>()
  #report: ScanReport = { files: 0, truncated: false }
  /** font name → prefix seen in the code → how often, for prefixes we do NOT expect */
  #otherPrefixes = new Map<string, Map<string, number>>()
  #scanning = false
  #emitter = new vscode.EventEmitter<void>()
  readonly onDidChange = this.#emitter.event

  constructor(private registry: IconFontRegistry) {}

  get scanning(): boolean { return this.#scanning }
  get report(): ScanReport { return this.#report }

  /** Icons sorted by use count, unused first — the actionable end of the list. */
  all(): IconUsage[] {
    return [...this.#usage.values()].sort((a, b) =>
      a.sites.length - b.sites.length || a.icon.glyph.name.localeCompare(b.icon.glyph.name))
  }

  for(icon: IconRef): IconUsage | undefined {
    return this.#usage.get(`${icon.font.name}/${icon.glyph.name}`)
  }

  get unused(): IconUsage[] { return this.all().filter((u) => u.sites.length === 0) }

  /**
   * The generated stylesheets, per font: not usage, but worth one click.
   *
   * Configured output first (whether or not it exists yet), then anything else the
   * scan recognised as generated.
   */
  generatedFor(font: IconFont): vscode.Uri[] {
    const root = vscode.workspace.getWorkspaceFolder(font.uri)?.uri ?? vscode.Uri.joinPath(font.uri, '..')
    const configured = outputPaths({ ...font.project, output: resolveOutputConfig(font) })
      .filter((p) => /\.(css|scss|less|json|dart|d\.ts)$/i.test(p))
      .map((p) => vscode.Uri.joinPath(root, p))
    const seen = new Set(configured.map((u) => u.toString()))
    return [...configured, ...[...this.#generated].filter((u) => !seen.has(u)).map((u) => vscode.Uri.parse(u))]
  }

  /**
   * A prefix the code uses that the font does not.
   *
   * The commonest reason a scan reports everything as unused is simply that the font's
   * prefix and the codebase disagree — an import renamed `alpimaps-` to `app-`, say.
   * Without this the panel just says "25 unused" and leaves you to work out why.
   */
  likelyPrefix(fontName: string): { prefix: string; count: number } | undefined {
    const seen = this.#otherPrefixes.get(fontName)
    if (!seen) return undefined
    const best = [...seen.entries()].sort((a, b) => b[1] - a[1])[0]
    return best && best[1] >= 2 ? { prefix: best[0], count: best[1] } : undefined
  }

  async scan(): Promise<void> {
    if (this.#scanning) return
    this.#scanning = true
    this.#emitter.fire()
    try {
      const config = vscode.workspace.getConfiguration('iconotype')
      const include = config.get<string>('usage.include') || DEFAULT_INCLUDE
      const exclude = config.get<string>('usage.exclude') || this.#excludeGlob()
      const limit = Math.max(1, config.get<number>('usage.maxFiles') || DEFAULT_FILE_LIMIT)

      const icons = this.registry.icons()
      const next = new Map<string, IconUsage>(
        icons.map((icon) => [`${icon.font.name}/${icon.glyph.name}`, { icon, sites: [] }]))

      this.#generated = new Set<string>()
      const pattern = referencePattern(this.registry.prefixes)
      /**
       * `something-home` where `home` is one of the font's icons but `something-` is
       * not its prefix. Bounded to fonts of a sane size: this compiles every icon name
       * into one alternation, and runs it over every file in the workspace.
       */
      const nearMiss = this.registry.fonts.map((font) => {
        const names = font.project.sets.flatMap((s) => s.glyphs).map((g) => g.name)
        if (!names.length || names.length > 500) return null
        const escaped = names.map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
        return {
          font,
          pattern: new RegExp(`([a-zA-Z][a-zA-Z0-9_]*-)(?:${escaped.join('|')})(?![a-zA-Z0-9_-])`, 'g'),
          seen: new Map<string, number>(),
        }
      }).filter(Boolean) as Array<{ font: { name: string; prefix: string }; pattern: RegExp; seen: Map<string, number> }>

      if (pattern) {
        const generated = this.#generatedPaths()
        const files = await vscode.workspace.findFiles(include, exclude || undefined, limit)
        this.#report = { files: files.length, truncated: files.length >= limit }
        for (const uri of files) {
          // skip our own output, or every icon always looks used: the generated
          // stylesheet names every single one
          if (/\.(iconotype)\.json$/.test(uri.path)) continue
          if (generated.has(uri.path)) continue
          let text: string
          try {
            text = new TextDecoder().decode(await vscode.workspace.fs.readFile(uri))
          } catch {
            continue
          }
          if (text.length > 2_000_000) continue
          // a stylesheet generated somewhere else — by IcoMoon, or under an output
          // config this project no longer has — names every icon, so counting it would
          // report the whole font as used
          if (isGeneratedStylesheet(uri, text)) { this.#generated.add(uri.toString()); continue }
          const lines = text.split('\n')
          for (let line = 0; line < lines.length; line++) {
            for (const match of lines[line]!.matchAll(pattern)) {
              const hit = this.registry.match(match[0])
              const icon = this.registry.resolve(match[0])
              if (!icon || !hit) continue
              const entry = next.get(`${icon.font.name}/${icon.glyph.name}`)
              entry?.sites.push({
                uri, line, column: match.index!, text: lines[line]!.trim().slice(0, 120), prefix: hit.prefix,
              })
            }
          }
          for (const candidate of nearMiss) {
            for (const match of text.matchAll(candidate.pattern)) {
              const found = match[1]!
              if (found === candidate.font.prefix) continue
              candidate.seen.set(found, (candidate.seen.get(found) ?? 0) + 1)
            }
          }
        }
      }
      this.#usage = next
      this.#otherPrefixes = new Map(nearMiss.map((c) => [c.font.name, c.seen]))
    } finally {
      this.#scanning = false
      this.#emitter.fire()
    }
  }

  /**
   * Re-indexes one file, on save.
   *
   * A full workspace scan is too slow to run on every keystroke or save, but a stale
   * index quietly reports icons as unused after you delete their last reference.
   */
  updateFile(uri: vscode.Uri, text: string): void {
    if (!this.#usage.size) return          // nothing scanned yet; nothing to keep current
    if (this.#generatedPaths().has(uri.path)) return
    if (/\.(iconotype)\.json$/.test(uri.path)) return

    const pattern = referencePattern(this.registry.prefixes)
    if (!pattern) return

    for (const entry of this.#usage.values()) {
      entry.sites = entry.sites.filter((site) => site.uri.toString() !== uri.toString())
    }
    const lines = text.split('\n')
    for (let line = 0; line < lines.length; line++) {
      for (const match of lines[line]!.matchAll(pattern)) {
        const icon = this.registry.resolve(match[0])
        if (!icon) continue
        this.#usage.get(`${icon.font.name}/${icon.glyph.name}`)?.sites.push({
          uri, line, column: match.index!, text: lines[line]!.trim().slice(0, 120),
          prefix: this.registry.match(match[0])?.prefix ?? icon.font.prefix,
        })
      }
    }
    this.#emitter.fire()
  }

  /**
   * The configured directories, plus whatever the workspace already hides from search.
   *
   * `iconotype.usage.excludeDirs` is the list (defaulted, so it can be trimmed as well
   * as added to); `iconotype.usage.useWorkspaceExcludes` lifts `search.exclude` and
   * `files.exclude` on top, because a repo that has told VSCode to ignore its build
   * output has told us too. `iconotype.usage.exclude` overrides the lot with a raw
   * glob for anything these cannot express.
   */
  #excludeGlob(): string {
    const config = vscode.workspace.getConfiguration('iconotype')
    const dirs = new Set(config.get<string[]>('usage.excludeDirs') ?? DEFAULT_EXCLUDE_DIRS)

    if (config.get<boolean>('usage.useWorkspaceExcludes', true)) {
      for (const section of ['search.exclude', 'files.exclude']) {
        const [key, name] = section.split('.') as [string, string]
        const patterns = vscode.workspace.getConfiguration(key).get<Record<string, boolean>>(name) ?? {}
        for (const [pattern, on] of Object.entries(patterns)) {
          if (!on) continue
          // only lift the plain `**/name` forms into our list; anything fancier stays
          // out rather than risking a malformed glob
          const match = /^\*\*\/([A-Za-z0-9_.-]+)(\/\*\*)?$/.exec(pattern)
          if (match) dirs.add(match[1]!)
        }
      }
    }
    return excludeGlobFor(dirs)
  }

  /** Absolute paths of every file a Iconotype export writes. */
  #generatedPaths(): Set<string> {
    const out = new Set<string>()
    for (const font of this.registry.fonts) {
      const root = vscode.workspace.getWorkspaceFolder(font.uri)?.uri
      if (!root) continue
      const config = resolveOutputConfig(font)
      const add = (paths?: Paths) => {
        for (const rel of asPaths(paths)) out.add(vscode.Uri.joinPath(root, rel).path)
      }
      for (const style of config.styles ?? []) add(style.path)
      add(config.types?.path)
      add(config.sprite?.path)
      add(config.demo?.path)
    }
    return out
  }

  dispose(): void { this.#emitter.dispose() }
}

type UsageNode =
  | { kind: 'group'; used: boolean; items: IconUsage[] }
  | { kind: 'icon'; usage: IconUsage }
  | { kind: 'site'; usage: IconUsage; site: UsageSite }
  | { kind: 'generatedGroup'; files: Array<{ font: IconFont; uri: vscode.Uri }> }
  | { kind: 'generated'; font: IconFont; uri: vscode.Uri }

/** The "Icon Usage" view. */
/**
 * Pick one of an icon's reference sites, the way Quick Open picks a file.
 *
 * The flat list this replaced made you commit before you could look: every row read
 * `some/long/path.svelte:41`, the paths crowded out the code, and choosing wrong meant
 * an editor you did not want and a trip back. So it borrows what Quick Open already
 * teaches — the file name is a separator over its own hits, each row leads with the
 * line of code, and arrowing through previews the site in the editor behind.
 *
 * Cancelling restores the editor that was open before, because browsing references
 * should cost nothing if you decide against all of them.
 */
export type UsagePickItem = vscode.QuickPickItem & { site?: UsageSite }

/** The rows, split out from the dialog so the grouping is testable on its own. */
export function usagePickItems(sites: UsageSite[]): UsagePickItem[] {
  const ordered = [...sites].sort((a, b) =>
    a.uri.path.localeCompare(b.uri.path) || a.line - b.line || a.column - b.column)

  const items: UsagePickItem[] = []
  let file: string | undefined
  for (const site of ordered) {
    if (site.uri.path !== file) {
      file = site.uri.path
      items.push({
        label: vscode.workspace.asRelativePath(site.uri),
        kind: vscode.QuickPickItemKind.Separator,
      })
    }
    items.push({
      // the code first: it is what tells you whether this is the site you meant
      label: site.text.trim() || vscode.workspace.asRelativePath(site.uri),
      description: `${site.line + 1}:${site.column + 1}`,
      site,
    })
  }
  return items
}

export async function pickUsageSite(
  sites: UsageSite[],
  opts: { title: string; rangeOf: (site: UsageSite) => vscode.Range },
): Promise<UsageSite | undefined> {
  const items = usagePickItems(sites)

  // where to put things back if nothing is chosen — previewing walks over the editor
  const before = vscode.window.activeTextEditor
  const restore = before && !before.document.isClosed
    ? { document: before.document, selection: before.selection, viewColumn: before.viewColumn }
    : undefined

  const quickPick = vscode.window.createQuickPick<UsagePickItem>()
  quickPick.title = opts.title
  quickPick.placeholder = 'Go to reference'
  quickPick.matchOnDescription = true
  quickPick.items = items

  let chosen: UsageSite | undefined
  try {
    await new Promise<void>((resolve) => {
      quickPick.onDidChangeActive(([item]) => {
        if (!item?.site) return
        void vscode.window.showTextDocument(item.site.uri, {
          preview: true, preserveFocus: true, selection: opts.rangeOf(item.site),
        })
      })
      quickPick.onDidAccept(() => { chosen = quickPick.activeItems[0]?.site; quickPick.hide() })
      quickPick.onDidHide(() => resolve())
      quickPick.show()
    })
  } finally {
    quickPick.dispose()
  }

  if (!chosen && restore) {
    await vscode.window.showTextDocument(restore.document, {
      viewColumn: restore.viewColumn, selection: restore.selection, preview: false,
    })
  }
  return chosen
}

export class UsageTreeProvider implements vscode.TreeDataProvider<UsageNode> {
  #emitter = new vscode.EventEmitter<UsageNode | undefined>()
  readonly onDidChangeTreeData = this.#emitter.event

  constructor(private index: UsageIndex, private registry?: IconFontRegistry) {
    index.onDidChange(() => this.#emitter.fire(undefined))
  }

  refresh(): void { this.#emitter.fire(undefined) }

  getTreeItem(node: UsageNode): vscode.TreeItem {
    if (node.kind === 'generatedGroup') {
      const item = new vscode.TreeItem(`Generated (${node.files.length})`, vscode.TreeItemCollapsibleState.Collapsed)
      item.description = 'not counted as usage'
      item.iconPath = new vscode.ThemeIcon('file-code')
      item.tooltip = 'Stylesheets a build writes. They name every icon, so counting them would make the whole font look used.'
      return item
    }

    if (node.kind === 'generated') {
      const item = new vscode.TreeItem(
        vscode.workspace.asRelativePath(node.uri), vscode.TreeItemCollapsibleState.None)
      item.description = node.font.name
      item.resourceUri = node.uri
      item.iconPath = new vscode.ThemeIcon('go-to-file')
      item.command = { command: 'vscode.open', title: 'Open', arguments: [node.uri] }
      return item
    }

    if (node.kind === 'group') {
      const total = node.items.reduce((n, u) => n + u.sites.length, 0)
      const item = new vscode.TreeItem(
        node.used ? `Used (${node.items.length})` : `Unused (${node.items.length})`,
        // the used group opens on its own: seeing WHERE an icon is used is the point of
        // the view, and it was previously buried under every unused icon
        node.used ? vscode.TreeItemCollapsibleState.Expanded : vscode.TreeItemCollapsibleState.Collapsed,
      )
      item.description = node.used ? `${total} reference(s)` : 'never referenced'
      item.iconPath = new vscode.ThemeIcon(node.used ? 'check' : 'circle-slash')
      item.contextValue = node.used ? 'iconotype.usedGroup' : 'iconotype.unusedGroup'
      return item
    }

    if (node.kind === 'site') {
      const item = new vscode.TreeItem(node.site.text || '(line)', vscode.TreeItemCollapsibleState.None)
      item.description = `${vscode.workspace.asRelativePath(node.site.uri)}:${node.site.line + 1}`
      item.resourceUri = node.site.uri
      item.command = {
        command: 'vscode.open',
        title: 'Open',
        arguments: [node.site.uri, {
          selection: new vscode.Range(node.site.line, node.site.column, node.site.line, node.site.column),
        }],
      }
      return item
    }

    const { icon, sites } = node.usage
    const item = new vscode.TreeItem(
      `${icon.font.prefix}${icon.glyph.name}`,
      sites.length ? vscode.TreeItemCollapsibleState.Expanded : vscode.TreeItemCollapsibleState.None,
    )
    item.description = sites.length ? `${sites.length} use(s)` : 'unused'
    item.iconPath = new vscode.ThemeIcon(sites.length ? 'symbol-color' : 'circle-slash')
    item.contextValue = sites.length ? 'iconotype.usedIcon' : 'iconotype.unusedIcon'
    item.tooltip = `${icon.font.name} · ${icon.codepoints.map((c) => 'U+' + c.toString(16)).join(' ')}`
    return item
  }

  getChildren(node?: UsageNode): UsageNode[] {
    if (!node) {
      const all = this.index.all()
      if (!all.length) return []
      const used = all.filter((u) => u.sites.length).sort((a, b) =>
        b.sites.length - a.sites.length || a.icon.glyph.name.localeCompare(b.icon.glyph.name))
      const unused = all.filter((u) => !u.sites.length)
      const groups: UsageNode[] = []
      if (used.length) groups.push({ kind: 'group', used: true, items: used })
      if (unused.length) groups.push({ kind: 'group', used: false, items: unused })

      const files = (this.registry?.fonts ?? []).flatMap((font) =>
        this.index.generatedFor(font).map((uri) => ({ font, uri })))
      if (files.length) groups.push({ kind: 'generatedGroup', files })
      return groups
    }
    if (node.kind === 'generatedGroup') {
      return node.files.map(({ font, uri }) => ({ kind: 'generated' as const, font, uri }))
    }
    if (node.kind === 'group') return node.items.map((usage) => ({ kind: 'icon', usage }))
    if (node.kind === 'icon') return node.usage.sites.map((site) => ({ kind: 'site', usage: node.usage, site }))
    return []
  }
}
